<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NacionalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Deshabilitar las restricciones de claves foráneas temporalmente
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // Limpia la tabla antes de insertar
        DB::table('nacionalidades')->truncate();

        $this->command->info('Cargando Paises...');

        // Otra manera de cargar es:
        $nacionalidades = [
            ['idNacionalidad' => 1, 'abreviacion' => 'AF', 'nacion' => 'Afganistán'],
            ['idNacionalidad' => 2, 'abreviacion' => 'AX', 'nacion' => 'Islas Gland'],
            ['idNacionalidad' => 3, 'abreviacion' => 'AL', 'nacion' => 'Albania'],
            ['idNacionalidad' => 4, 'abreviacion' => 'DE', 'nacion' => 'Alemania'],
            ['idNacionalidad' => 5, 'abreviacion' => 'AD', 'nacion' => 'Andorra'],
            ['idNacionalidad' => 6, 'abreviacion' => 'AO', 'nacion' => 'Angola'],
            ['idNacionalidad' => 7, 'abreviacion' => 'AI', 'nacion' => 'Anguilla'],
            ['idNacionalidad' => 8, 'abreviacion' => 'AQ', 'nacion' => 'Antártida'],
            ['idNacionalidad' => 9, 'abreviacion' => 'AG', 'nacion' => 'Antigua y Barbuda'],
            ['idNacionalidad' => 10, 'abreviacion' => 'AN', 'nacion' => 'Antillas Holandesas'],
            ['idNacionalidad' => 11, 'abreviacion' => 'SA', 'nacion' => 'Arabia Saudí'],
            ['idNacionalidad' => 12, 'abreviacion' => 'DZ', 'nacion' => 'Argelia'],
            ['idNacionalidad' => 13, 'abreviacion' => 'AR', 'nacion' => 'Argentina'],
            ['idNacionalidad' => 14, 'abreviacion' => 'AM', 'nacion' => 'Armenia'],
            ['idNacionalidad' => 15, 'abreviacion' => 'AW', 'nacion' => 'Aruba'],
            ['idNacionalidad' => 16, 'abreviacion' => 'AU', 'nacion' => 'Australia'],
            ['idNacionalidad' => 17, 'abreviacion' => 'AT', 'nacion' => 'Austria'],
            ['idNacionalidad' => 18, 'abreviacion' => 'AZ', 'nacion' => 'Azerbaiyán'],
            ['idNacionalidad' => 19, 'abreviacion' => 'BS', 'nacion' => 'Bahamas'],
            ['idNacionalidad' => 20, 'abreviacion' => 'BH', 'nacion' => 'Bahréin'],
            ['idNacionalidad' => 21, 'abreviacion' => 'BD', 'nacion' => 'Bangladesh'],
            ['idNacionalidad' => 22, 'abreviacion' => 'BB', 'nacion' => 'Barbados'],
            ['idNacionalidad' => 23, 'abreviacion' => 'BY', 'nacion' => 'Bielorrusia'],
            ['idNacionalidad' => 24, 'abreviacion' => 'BE', 'nacion' => 'Bélgica'],
            ['idNacionalidad' => 25, 'abreviacion' => 'BZ', 'nacion' => 'Belice'],
            ['idNacionalidad' => 26, 'abreviacion' => 'BJ', 'nacion' => 'Benin'],
            ['idNacionalidad' => 27, 'abreviacion' => 'BM', 'nacion' => 'Bermudas'],
            ['idNacionalidad' => 28, 'abreviacion' => 'BT', 'nacion' => 'Bhután'],
            ['idNacionalidad' => 29, 'abreviacion' => 'BO', 'nacion' => 'Bolivia'],
            ['idNacionalidad' => 30, 'abreviacion' => 'BA', 'nacion' => 'Bosnia y Herzegovina'],
            ['idNacionalidad' => 31, 'abreviacion' => 'BW', 'nacion' => 'Botsuana'],
            ['idNacionalidad' => 32, 'abreviacion' => 'BV', 'nacion' => 'Isla Bouvet'],
            ['idNacionalidad' => 33, 'abreviacion' => 'BR', 'nacion' => 'Brasil'],
            ['idNacionalidad' => 34, 'abreviacion' => 'BN', 'nacion' => 'Brunéi'],
            ['idNacionalidad' => 35, 'abreviacion' => 'BG', 'nacion' => 'Bulgaria'],
            ['idNacionalidad' => 36, 'abreviacion' => 'BF', 'nacion' => 'Burkina Faso'],
            ['idNacionalidad' => 37, 'abreviacion' => 'BI', 'nacion' => 'Burundi'],
            ['idNacionalidad' => 38, 'abreviacion' => 'CV', 'nacion' => 'Cabo Verde'],
            ['idNacionalidad' => 39, 'abreviacion' => 'KY', 'nacion' => 'Islas Caimán'],
            ['idNacionalidad' => 40, 'abreviacion' => 'KH', 'nacion' => 'Camboya'],
            ['idNacionalidad' => 41, 'abreviacion' => 'CM', 'nacion' => 'Camerún'],
            ['idNacionalidad' => 42, 'abreviacion' => 'CA', 'nacion' => 'Canadá'],
            ['idNacionalidad' => 43, 'abreviacion' => 'CF', 'nacion' => 'República Centroafricana'],
            ['idNacionalidad' => 44, 'abreviacion' => 'TD', 'nacion' => 'Chad'],
            ['idNacionalidad' => 45, 'abreviacion' => 'CZ', 'nacion' => 'República Checa'],
            ['idNacionalidad' => 46, 'abreviacion' => 'CL', 'nacion' => 'Chile'],
            ['idNacionalidad' => 47, 'abreviacion' => 'CN', 'nacion' => 'China'],
            ['idNacionalidad' => 48, 'abreviacion' => 'CY', 'nacion' => 'Chipre'],
            ['idNacionalidad' => 49, 'abreviacion' => 'CX', 'nacion' => 'Isla de Navidad'],
            ['idNacionalidad' => 50, 'abreviacion' => 'VA', 'nacion' => 'Ciudad del Vaticano'],
            ['idNacionalidad' => 51, 'abreviacion' => 'CC', 'nacion' => 'Islas Cocos'],
            ['idNacionalidad' => 52, 'abreviacion' => 'CO', 'nacion' => 'Colombia'],
            ['idNacionalidad' => 53, 'abreviacion' => 'KM', 'nacion' => 'Comoras'],
            ['idNacionalidad' => 54, 'abreviacion' => 'CD', 'nacion' => 'República Democrática del Congo'],
            ['idNacionalidad' => 55, 'abreviacion' => 'CG', 'nacion' => 'Congo'],
            ['idNacionalidad' => 56, 'abreviacion' => 'CK', 'nacion' => 'Islas Cook'],
            ['idNacionalidad' => 57, 'abreviacion' => 'KP', 'nacion' => 'Corea del Norte'],
            ['idNacionalidad' => 58, 'abreviacion' => 'KR', 'nacion' => 'Corea del Sur'],
            ['idNacionalidad' => 59, 'abreviacion' => 'CI', 'nacion' => 'Costa de Marfil'],
            ['idNacionalidad' => 60, 'abreviacion' => 'CR', 'nacion' => 'Costa Rica'],
            ['idNacionalidad' => 61, 'abreviacion' => 'HR', 'nacion' => 'Croacia'],
            ['idNacionalidad' => 62, 'abreviacion' => 'CU', 'nacion' => 'Cuba'],
            ['idNacionalidad' => 63, 'abreviacion' => 'DK', 'nacion' => 'Dinamarca'],
            ['idNacionalidad' => 64, 'abreviacion' => 'DM', 'nacion' => 'Dominica'],
            ['idNacionalidad' => 65, 'abreviacion' => 'DO', 'nacion' => 'República Dominicana'],
            ['idNacionalidad' => 66, 'abreviacion' => 'EC', 'nacion' => 'Ecuador'],
            ['idNacionalidad' => 67, 'abreviacion' => 'EG', 'nacion' => 'Egipto'],
            ['idNacionalidad' => 68, 'abreviacion' => 'SV', 'nacion' => 'El Salvador'],
            ['idNacionalidad' => 69, 'abreviacion' => 'AE', 'nacion' => 'Emiratos Árabes Unidos'],
            ['idNacionalidad' => 70, 'abreviacion' => 'ER', 'nacion' => 'Eritrea'],
            ['idNacionalidad' => 71, 'abreviacion' => 'SK', 'nacion' => 'Eslovaquia'],
            ['idNacionalidad' => 72, 'abreviacion' => 'SI', 'nacion' => 'Eslovenia'],
            ['idNacionalidad' => 73, 'abreviacion' => 'ES', 'nacion' => 'España'],
            ['idNacionalidad' => 74, 'abreviacion' => 'UM', 'nacion' => 'Islas ultramarinas de Estados Unidos'],
            ['idNacionalidad' => 75, 'abreviacion' => 'US', 'nacion' => 'Estados Unidos'],
            ['idNacionalidad' => 76, 'abreviacion' => 'EE', 'nacion' => 'Estonia'],
            ['idNacionalidad' => 77, 'abreviacion' => 'ET', 'nacion' => 'Etiopía'],
            ['idNacionalidad' => 78, 'abreviacion' => 'FO', 'nacion' => 'Islas Feroe'],
            ['idNacionalidad' => 79, 'abreviacion' => 'PH', 'nacion' => 'Filipinas'],
            ['idNacionalidad' => 80, 'abreviacion' => 'FI', 'nacion' => 'Finlandia'],
            ['idNacionalidad' => 81, 'abreviacion' => 'FJ', 'nacion' => 'Fiyi'],
            ['idNacionalidad' => 82, 'abreviacion' => 'FR', 'nacion' => 'Francia'],
            ['idNacionalidad' => 83, 'abreviacion' => 'GA', 'nacion' => 'Gabón'],
            ['idNacionalidad' => 84, 'abreviacion' => 'GM', 'nacion' => 'Gambia'],
            ['idNacionalidad' => 85, 'abreviacion' => 'GE', 'nacion' => 'Georgia'],
            ['idNacionalidad' => 86, 'abreviacion' => 'GS', 'nacion' => 'Islas Georgias del Sur y Sandwich del Sur'],
            ['idNacionalidad' => 87, 'abreviacion' => 'GH', 'nacion' => 'Ghana'],
            ['idNacionalidad' => 88, 'abreviacion' => 'GI', 'nacion' => 'Gibraltar'],
            ['idNacionalidad' => 89, 'abreviacion' => 'GD', 'nacion' => 'Granada'],
            ['idNacionalidad' => 90, 'abreviacion' => 'GR', 'nacion' => 'Grecia'],
            ['idNacionalidad' => 91, 'abreviacion' => 'GL', 'nacion' => 'Groenlandia'],
            ['idNacionalidad' => 92, 'abreviacion' => 'GP', 'nacion' => 'Guadalupe'],
            ['idNacionalidad' => 93, 'abreviacion' => 'GU', 'nacion' => 'Guam'],
            ['idNacionalidad' => 94, 'abreviacion' => 'GT', 'nacion' => 'Guatemala'],
            ['idNacionalidad' => 95, 'abreviacion' => 'GF', 'nacion' => 'Guayana Francesa'],
            ['idNacionalidad' => 96, 'abreviacion' => 'GN', 'nacion' => 'Guinea'],
            ['idNacionalidad' => 97, 'abreviacion' => 'GQ', 'nacion' => 'Guinea Ecuatorial'],
            ['idNacionalidad' => 98, 'abreviacion' => 'GW', 'nacion' => 'Guinea-Bissau'],
            ['idNacionalidad' => 99, 'abreviacion' => 'GY', 'nacion' => 'Guyana'],
            ['idNacionalidad' => 100, 'abreviacion' => 'HT', 'nacion' => 'Haití'],
            ['idNacionalidad' => 101, 'abreviacion' => 'HM', 'nacion' => 'Islas Heard y McDonald'],
            ['idNacionalidad' => 102, 'abreviacion' => 'HN', 'nacion' => 'Honduras'],
            ['idNacionalidad' => 103, 'abreviacion' => 'HK', 'nacion' => 'Hong Kong'],
            ['idNacionalidad' => 104, 'abreviacion' => 'HU', 'nacion' => 'Hungría'],
            ['idNacionalidad' => 105, 'abreviacion' => 'IN', 'nacion' => 'India'],
            ['idNacionalidad' => 106, 'abreviacion' => 'ID', 'nacion' => 'Indonesia'],
            ['idNacionalidad' => 107, 'abreviacion' => 'IR', 'nacion' => 'Irán'],
            ['idNacionalidad' => 108, 'abreviacion' => 'IQ', 'nacion' => 'Iraq'],
            ['idNacionalidad' => 109, 'abreviacion' => 'IE', 'nacion' => 'Irlanda'],
            ['idNacionalidad' => 110, 'abreviacion' => 'IS', 'nacion' => 'Islandia'],
            ['idNacionalidad' => 111, 'abreviacion' => 'IL', 'nacion' => 'Israel'],
            ['idNacionalidad' => 112, 'abreviacion' => 'IT', 'nacion' => 'Italia'],
            ['idNacionalidad' => 113, 'abreviacion' => 'JM', 'nacion' => 'Jamaica'],
            ['idNacionalidad' => 114, 'abreviacion' => 'JP', 'nacion' => 'Japón'],
            ['idNacionalidad' => 115, 'abreviacion' => 'JO', 'nacion' => 'Jordania'],
            ['idNacionalidad' => 116, 'abreviacion' => 'KZ', 'nacion' => 'Kazajstán'],
            ['idNacionalidad' => 117, 'abreviacion' => 'KE', 'nacion' => 'Kenia'],
            ['idNacionalidad' => 118, 'abreviacion' => 'KG', 'nacion' => 'Kirguistán'],
            ['idNacionalidad' => 119, 'abreviacion' => 'KI', 'nacion' => 'Kiribati'],
            ['idNacionalidad' => 120, 'abreviacion' => 'KW', 'nacion' => 'Kuwait'],
            ['idNacionalidad' => 121, 'abreviacion' => 'LA', 'nacion' => 'Laos'],
            ['idNacionalidad' => 122, 'abreviacion' => 'LS', 'nacion' => 'Lesotho'],
            ['idNacionalidad' => 123, 'abreviacion' => 'LV', 'nacion' => 'Letonia'],
            ['idNacionalidad' => 124, 'abreviacion' => 'LB', 'nacion' => 'Líbano'],
            ['idNacionalidad' => 125, 'abreviacion' => 'LR', 'nacion' => 'Liberia'],
            ['idNacionalidad' => 126, 'abreviacion' => 'LY', 'nacion' => 'Libia'],
            ['idNacionalidad' => 127, 'abreviacion' => 'LI', 'nacion' => 'Liechtenstein'],
            ['idNacionalidad' => 128, 'abreviacion' => 'LT', 'nacion' => 'Lituania'],
            ['idNacionalidad' => 129, 'abreviacion' => 'LU', 'nacion' => 'Luxemburgo'],
            ['idNacionalidad' => 130, 'abreviacion' => 'MO', 'nacion' => 'Macao'],
            ['idNacionalidad' => 131, 'abreviacion' => 'MK', 'nacion' => 'ARY Macedonia'],
            ['idNacionalidad' => 132, 'abreviacion' => 'MG', 'nacion' => 'Madagascar'],
            ['idNacionalidad' => 133, 'abreviacion' => 'MY', 'nacion' => 'Malasia'],
            ['idNacionalidad' => 134, 'abreviacion' => 'MW', 'nacion' => 'Malawi'],
            ['idNacionalidad' => 135, 'abreviacion' => 'MV', 'nacion' => 'Maldivas'],
            ['idNacionalidad' => 136, 'abreviacion' => 'ML', 'nacion' => 'Malí'],
            ['idNacionalidad' => 137, 'abreviacion' => 'MT', 'nacion' => 'Malta'],
            ['idNacionalidad' => 138, 'abreviacion' => 'FK', 'nacion' => 'Islas Malvinas'],
            ['idNacionalidad' => 139, 'abreviacion' => 'MP', 'nacion' => 'Islas Marianas del Norte'],
            ['idNacionalidad' => 140, 'abreviacion' => 'MA', 'nacion' => 'Marruecos'],
            ['idNacionalidad' => 141, 'abreviacion' => 'MH', 'nacion' => 'Islas Marshall'],
            ['idNacionalidad' => 142, 'abreviacion' => 'MQ', 'nacion' => 'Martinica'],
            ['idNacionalidad' => 143, 'abreviacion' => 'MU', 'nacion' => 'Mauricio'],
            ['idNacionalidad' => 144, 'abreviacion' => 'MR', 'nacion' => 'Mauritania'],
            ['idNacionalidad' => 145, 'abreviacion' => 'YT', 'nacion' => 'Mayotte'],
            ['idNacionalidad' => 146, 'abreviacion' => 'MX', 'nacion' => 'México'],
            ['idNacionalidad' => 147, 'abreviacion' => 'FM', 'nacion' => 'Micronesia'],
            ['idNacionalidad' => 148, 'abreviacion' => 'MD', 'nacion' => 'Moldavia'],
            ['idNacionalidad' => 149, 'abreviacion' => 'MC', 'nacion' => 'Mónaco'],
            ['idNacionalidad' => 150, 'abreviacion' => 'MN', 'nacion' => 'Mongolia'],
            ['idNacionalidad' => 151, 'abreviacion' => 'MS', 'nacion' => 'Montserrat'],
            ['idNacionalidad' => 152, 'abreviacion' => 'MZ', 'nacion' => 'Mozambique'],
            ['idNacionalidad' => 153, 'abreviacion' => 'MM', 'nacion' => 'Myanmar'],
            ['idNacionalidad' => 154, 'abreviacion' => 'NA', 'nacion' => 'Namibia'],
            ['idNacionalidad' => 155, 'abreviacion' => 'NR', 'nacion' => 'Nauru'],
            ['idNacionalidad' => 156, 'abreviacion' => 'NP', 'nacion' => 'Nepal'],
            ['idNacionalidad' => 157, 'abreviacion' => 'NI', 'nacion' => 'Nicaragua'],
            ['idNacionalidad' => 158, 'abreviacion' => 'NE', 'nacion' => 'Níger'],
            ['idNacionalidad' => 159, 'abreviacion' => 'NG', 'nacion' => 'Nigeria'],
            ['idNacionalidad' => 160, 'abreviacion' => 'NU', 'nacion' => 'Niue'],
            ['idNacionalidad' => 161, 'abreviacion' => 'NF', 'nacion' => 'Isla Norfolk'],
            ['idNacionalidad' => 162, 'abreviacion' => 'NO', 'nacion' => 'Noruega'],
            ['idNacionalidad' => 163, 'abreviacion' => 'NC', 'nacion' => 'Nueva Caledonia'],
            ['idNacionalidad' => 164, 'abreviacion' => 'NZ', 'nacion' => 'Nueva Zelanda'],
            ['idNacionalidad' => 165, 'abreviacion' => 'OM', 'nacion' => 'Omán'],
            ['idNacionalidad' => 166, 'abreviacion' => 'NL', 'nacion' => 'Países Bajos'],
            ['idNacionalidad' => 167, 'abreviacion' => 'PK', 'nacion' => 'Pakistán'],
            ['idNacionalidad' => 168, 'abreviacion' => 'PW', 'nacion' => 'Palau'],
            ['idNacionalidad' => 169, 'abreviacion' => 'PS', 'nacion' => 'Palestina'],
            ['idNacionalidad' => 170, 'abreviacion' => 'PA', 'nacion' => 'Panamá'],
            ['idNacionalidad' => 171, 'abreviacion' => 'PG', 'nacion' => 'Papúa Nueva Guinea'],
            ['idNacionalidad' => 172, 'abreviacion' => 'PY', 'nacion' => 'Paraguay'],
            ['idNacionalidad' => 173, 'abreviacion' => 'PE', 'nacion' => 'Perú'],
            ['idNacionalidad' => 174, 'abreviacion' => 'PN', 'nacion' => 'Islas Pitcairn'],
            ['idNacionalidad' => 175, 'abreviacion' => 'PF', 'nacion' => 'Polinesia Francesa'],
            ['idNacionalidad' => 176, 'abreviacion' => 'PL', 'nacion' => 'Polonia'],
            ['idNacionalidad' => 177, 'abreviacion' => 'PT', 'nacion' => 'Portugal'],
            ['idNacionalidad' => 178, 'abreviacion' => 'PR', 'nacion' => 'Puerto Rico'],
            ['idNacionalidad' => 179, 'abreviacion' => 'QA', 'nacion' => 'Qatar'],
            ['idNacionalidad' => 180, 'abreviacion' => 'GB', 'nacion' => 'Reino Unido'],
            ['idNacionalidad' => 181, 'abreviacion' => 'RE', 'nacion' => 'Reunión'],
            ['idNacionalidad' => 182, 'abreviacion' => 'RW', 'nacion' => 'Ruanda'],
            ['idNacionalidad' => 183, 'abreviacion' => 'RO', 'nacion' => 'Rumania'],
            ['idNacionalidad' => 184, 'abreviacion' => 'RU', 'nacion' => 'Rusia'],
            ['idNacionalidad' => 185, 'abreviacion' => 'EH', 'nacion' => 'Sahara Occidental'],
            ['idNacionalidad' => 186, 'abreviacion' => 'SB', 'nacion' => 'Islas Salomón'],
            ['idNacionalidad' => 187, 'abreviacion' => 'WS', 'nacion' => 'Samoa'],
            ['idNacionalidad' => 188, 'abreviacion' => 'AS', 'nacion' => 'Samoa Americana'],
            ['idNacionalidad' => 189, 'abreviacion' => 'KN', 'nacion' => 'San Cristóbal y Nevis'],
            ['idNacionalidad' => 190, 'abreviacion' => 'SM', 'nacion' => 'San Marino'],
            ['idNacionalidad' => 191, 'abreviacion' => 'PM', 'nacion' => 'San Pedro y Miquelón'],
            ['idNacionalidad' => 192, 'abreviacion' => 'VC', 'nacion' => 'San Vicente y las Granadinas'],
            ['idNacionalidad' => 193, 'abreviacion' => 'SH', 'nacion' => 'Santa Helena'],
            ['idNacionalidad' => 194, 'abreviacion' => 'LC', 'nacion' => 'Santa Lucía'],
            ['idNacionalidad' => 195, 'abreviacion' => 'ST', 'nacion' => 'Santo Tomé y Príncipe'],
            ['idNacionalidad' => 196, 'abreviacion' => 'SN', 'nacion' => 'Senegal'],
            ['idNacionalidad' => 197, 'abreviacion' => 'CS', 'nacion' => 'Serbia y Montenegro'],
            ['idNacionalidad' => 198, 'abreviacion' => 'SC', 'nacion' => 'Seychelles'],
            ['idNacionalidad' => 199, 'abreviacion' => 'SL', 'nacion' => 'Sierra Leona'],
            ['idNacionalidad' => 200, 'abreviacion' => 'SG', 'nacion' => 'Singapur'],
            ['idNacionalidad' => 201, 'abreviacion' => 'SY', 'nacion' => 'Siria'],
            ['idNacionalidad' => 202, 'abreviacion' => 'SO', 'nacion' => 'Somalia'],
            ['idNacionalidad' => 203, 'abreviacion' => 'LK', 'nacion' => 'Sri Lanka'],
            ['idNacionalidad' => 204, 'abreviacion' => 'SZ', 'nacion' => 'Suazilandia'],
            ['idNacionalidad' => 205, 'abreviacion' => 'ZA', 'nacion' => 'Sudáfrica'],
            ['idNacionalidad' => 206, 'abreviacion' => 'SD', 'nacion' => 'Sudán'],
            ['idNacionalidad' => 207, 'abreviacion' => 'SE', 'nacion' => 'Suecia'],
            ['idNacionalidad' => 208, 'abreviacion' => 'CH', 'nacion' => 'Suiza'],
            ['idNacionalidad' => 209, 'abreviacion' => 'SR', 'nacion' => 'Surinam'],
            ['idNacionalidad' => 210, 'abreviacion' => 'SJ', 'nacion' => 'Svalbard y Jan Mayen'],
            ['idNacionalidad' => 211, 'abreviacion' => 'TH', 'nacion' => 'Tailandia'],
            ['idNacionalidad' => 212, 'abreviacion' => 'TW', 'nacion' => 'Taiwán'],
            ['idNacionalidad' => 213, 'abreviacion' => 'TZ', 'nacion' => 'Tanzania'],
            ['idNacionalidad' => 214, 'abreviacion' => 'TJ', 'nacion' => 'Tayikistán'],
            ['idNacionalidad' => 215, 'abreviacion' => 'IO', 'nacion' => 'Territorio Británico del Océano Índico'],
            ['idNacionalidad' => 216, 'abreviacion' => 'TF', 'nacion' => 'Territorios Australes Franceses'],
            ['idNacionalidad' => 217, 'abreviacion' => 'TL', 'nacion' => 'Timor Oriental'],
            ['idNacionalidad' => 218, 'abreviacion' => 'TG', 'nacion' => 'Togo'],
            ['idNacionalidad' => 219, 'abreviacion' => 'TK', 'nacion' => 'Tokelau'],
            ['idNacionalidad' => 220, 'abreviacion' => 'TO', 'nacion' => 'Tonga'],
            ['idNacionalidad' => 221, 'abreviacion' => 'TT', 'nacion' => 'Trinidad y Tobago'],
            ['idNacionalidad' => 222, 'abreviacion' => 'TN', 'nacion' => 'Túnez'],
            ['idNacionalidad' => 223, 'abreviacion' => 'TC', 'nacion' => 'Islas Turcas y Caicos'],
            ['idNacionalidad' => 224, 'abreviacion' => 'TM', 'nacion' => 'Turkmenistán'],
            ['idNacionalidad' => 225, 'abreviacion' => 'TR', 'nacion' => 'Turquía'],
            ['idNacionalidad' => 226, 'abreviacion' => 'TV', 'nacion' => 'Tuvalu'],
            ['idNacionalidad' => 227, 'abreviacion' => 'UA', 'nacion' => 'Ucrania'],
            ['idNacionalidad' => 228, 'abreviacion' => 'UG', 'nacion' => 'Uganda'],
            ['idNacionalidad' => 229, 'abreviacion' => 'UY', 'nacion' => 'Uruguay'],
            ['idNacionalidad' => 230, 'abreviacion' => 'UZ', 'nacion' => 'Uzbekistán'],
            ['idNacionalidad' => 231, 'abreviacion' => 'VU', 'nacion' => 'Vanuatu'],
            ['idNacionalidad' => 232, 'abreviacion' => 'VE', 'nacion' => 'Venezuela'],
            ['idNacionalidad' => 233, 'abreviacion' => 'VN', 'nacion' => 'Vietnam'],
            ['idNacionalidad' => 234, 'abreviacion' => 'VG', 'nacion' => 'Islas Vírgenes Británicas'],
            ['idNacionalidad' => 235, 'abreviacion' => 'VI', 'nacion' => 'Islas Vírgenes de los Estados Unidos'],
            ['idNacionalidad' => 236, 'abreviacion' => 'WF', 'nacion' => 'Wallis y Futuna'],
            ['idNacionalidad' => 237, 'abreviacion' => 'YE', 'nacion' => 'Yemen'],
            ['idNacionalidad' => 238, 'abreviacion' => 'DJ', 'nacion' => 'Yibuti'],
            ['idNacionalidad' => 239, 'abreviacion' => 'ZM', 'nacion' => 'Zambia'],
            ['idNacionalidad' => 240, 'abreviacion' => 'ZW', 'nacion' => 'Zimbabue']
        ];

        // Inserta los países en la tabla 'nacionalidad'
        DB::table('nacionalidades')->insert($nacionalidades);

        // Reactivar las restricciones de claves foráneas
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
